// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAcEn9LvB-T8IqMNlEiGVpevJ_wqhnZrI',
    appId: '1:386319475258:web:1f820944bc0e78064e8b03',
    messagingSenderId: '386319475258',
    projectId: 'otpverification-66200',
    authDomain: 'otpverification-66200.firebaseapp.com',
    storageBucket: 'otpverification-66200.appspot.com',
    measurementId: 'G-7E3Z0Q778T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNIikIB-hf60xHMCVCeferY9Q1sEe9ya8',
    appId: '1:386319475258:android:5200b8acd2ed46404e8b03',
    messagingSenderId: '386319475258',
    projectId: 'otpverification-66200',
    storageBucket: 'otpverification-66200.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDImM2EIV5Wpm1tY0ZQinEFfsxqY4_WyLU',
    appId: '1:386319475258:ios:7938883c4a9277024e8b03',
    messagingSenderId: '386319475258',
    projectId: 'otpverification-66200',
    storageBucket: 'otpverification-66200.appspot.com',
    iosBundleId: 'com.example.otpAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDImM2EIV5Wpm1tY0ZQinEFfsxqY4_WyLU',
    appId: '1:386319475258:ios:7938883c4a9277024e8b03',
    messagingSenderId: '386319475258',
    projectId: 'otpverification-66200',
    storageBucket: 'otpverification-66200.appspot.com',
    iosBundleId: 'com.example.otpAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAcEn9LvB-T8IqMNlEiGVpevJ_wqhnZrI',
    appId: '1:386319475258:web:36050d78a284abf34e8b03',
    messagingSenderId: '386319475258',
    projectId: 'otpverification-66200',
    authDomain: 'otpverification-66200.firebaseapp.com',
    storageBucket: 'otpverification-66200.appspot.com',
    measurementId: 'G-ZCS65KZDH2',
  );

}